### ISSUE TITLE
Error on window init

### ISSUE THREAD

**Issue by JTSJohnny** [jhi2/PyUi3#1]
@JPHutchins Hello again.
As the title suggests, there is an error on window init.
Can you please help me?
continued from the conversation on toga.

**Comment by JPHutchins** [comment]
Hello!  Can you post a code excerpt and the traceback?  Thanks!

**Comment by JTSJohnny** [comment]
PS C:\Users\johnd\source\repos\PyUi3> & "C:/Program Files/Python312/python.exe" c:/Users/johnd/source/repos/PyUi3/PyUI3/test.py
Traceback (most recent call last):
  File "c:\Users\johnd\source\repos\PyUi3\PyUI3\test.py", line 4, in <module>
    window = PyUI3.ApplicationWindow()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\PyUI3\__init__.py", line 37, in __init__
    self.app = App()
               ^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\PyUI3\__init__.py", line 28, in __init__
    super().__init__()
  File "C:\Program Files\Python312\Lib\site-packages\win32more\xaml.py", line 36, in __init__
    self._provider = XamlControlsXamlMetaDataProvider()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\win32more\Microsoft\UI\Xaml\XamlTypeInfo\__init__.py", line 26, in __init__
    super().__init__(move=win32more.Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider.CreateInstance(*args))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\win32more\_winrt.py", line 722, in __call__
    return _ro_activate_instance(cls._classid_, cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\win32more\_winrt.py", line 785, in _ro_activate_instance
    raise WinError(hr)
OSError: [WinError -2147221164] Class not registered

**Comment by JTSJohnny** [comment]
here is the code i used to test it(ai generated):
```python
import PyUI3

# Create a window
window = PyUI3.ApplicationWindow()

# Add some widgets
label = PyUI3.Label(window, "Welcome to PyUI3!", pos=(150, 50))
button = PyUI3.Button(window, "Click Me!", pos=(150, 100))
entry = PyUI3.Entry(window, pos=(150, 150))

# Define a callback function for the button
def button_click():
    label.text = f"Hello, {entry.text}!"

# Bind the callback to the button
button.on_click = button_click

# Start the main loop
window.run()
```

**Comment by JTSJohnny** [comment]
I think @ynkdir would be helpful with this.

**Comment by ynkdir** [comment]
"Class not registered" means that WindowsAppSDK is not initialized.
You need to initialize Com and WindowsAppSDK before using WinUI API.
See win32more.xaml.XamlApplication.Start() for detail.

Typical application code is

```python
from win32more.Microsoft.UI.Xaml import Window
from win32more.xaml import XamlApplication

class App(XamlApplication):
    def OnLaunched(self, args):
        # Now, Com and WindowsAppSDK were initialized.
        # You can use WinUI from here.
        win = Window()
        win.Activate()

XamlApplication.Start(App)
```

**Comment by JTSJohnny** [comment]
> "Class not registered" means that WindowsAppSDK is not initialized. You need to initialize Com and WindowsAppSDK before using WinUI API. See win32more.xaml.XamlApplication.Start() for detail.
> 
> Typical application code is
> 
> ```python
> from win32more.Microsoft.UI.Xaml import Window
> from win32more.xaml import XamlApplication
> 
> class App(XamlApplication):
>     def OnLaunched(self, args):
>         # Now, Com and WindowsAppSDK were initialized.
>         # You can use WinUI from here.
>         win = Window()
>         win.Activate()
> 
> XamlApplication.Start(App)
> ```

I will try that

**Comment by JTSJohnny** [comment]
No, Here is what i did in the run function: 
```python
 def run(self):
        for item in self.roster:
            self.win.Content = item
        XamlApplication.Start(self.app)
        self.win.Activate()

``` 
Please submit a PR to fix the issue.

**Comment by JTSJohnny** [comment]
So, I built a formatter, didint work AT ALL! I used it on this repo. I had to revert, so its fixed now

**Comment by JTSJohnny** [comment]
@ynkdir Did you see the post above the one above this one? There are a few mods to it, but still error

**Comment by JTSJohnny** [comment]
> So, I built a formatter, didint work AT ALL! I used it on this repo. I had to revert, so its fixed now

I know, right? did you see, it  look sorta-minified?

**Comment by ynkdir** [comment]
Did you try my example code?
It show you an empty window.
If I were you, I would start with a working code and gradually add my own code step by step, ensuring the program continues to work.
I don't write your library.

**Comment by JTSJohnny** [comment]
i know how to use win32more, but can you please contribute and help me fix the code?

**Comment by JTSJohnny** [comment]
@JPHutchins  @ynkdir  So, ChatGPT5 did it's thing and fixed my code:
```python
from win32more.Microsoft.UI.Xaml import Window
from win32more.xaml import XamlApplication

import PyUI3

class App(XamlApplication):
    def OnLaunched(self, args):
        # Initialize PyUI3 window after COM/WinUI are ready
        window = PyUI3.ApplicationWindow()

        label = PyUI3.Label(window, "Welcome to PyUI3!", pos=(150, 50))
        button = PyUI3.Button(window, "Click Me!", pos=(150, 100))
        entry = PyUI3.Entry(window, pos=(150, 150))

        def button_click():
            label.text = f"Hello, {entry.text}!"

        button.on_click = button_click

        window.run()  # Make sure this only activates content, not start XamlApplication again

XamlApplication.Start(App)

``` 
Im on linux right now but when i get to windows, i will test it.

**Comment by JTSJohnny** [comment]
I AM BACK

**Comment by JTSJohnny** [comment]
I am going to UN-Pull request this

**Comment by JTSJohnny** [comment]
That PR was noyt working. AT ALL.

**Comment by JTSJohnny** [comment]
I switched to linux full-time. Now I need a python wrapper for GTK.  Iam going to stop maintaiing this repo. If anyone wants to help out, let them.
